[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fitz>=0.0.1.dev2",
    "flask==3.1.0",
    "openpyxl==3.1.5",
    "pandas>=2.2.3",
    "pymupdf==1.25.0",
    "pypdf2==3.0.1",
]
